Various minor fixes
1. Use environment specfic python3 instead of hardcoding
2. Fail gracefully when entries in categories don't exist on disk
3. Do a version check of python. datetime.date.fromisoformat doesn't
    exist in python < 3.7

   Repro on twinpeaks
        $ python3.6 -c "import datetime; datetime.date.fromisoformat"
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
        AttributeError: type object 'datetime.date' has no attribute 'fromisoformat'